// Generated by OpenNext before the Worker entry is bundled.
// @ts-ignore OpenNext generates this module during the build.
import nextWorker from './.open-next/worker.js';
export { CfbWeekLiveFeed } from './src/durable-objects/cfb-week-live-feed';
import { handleCfbLive, handleCfbLiveSocket, handleCfbRelayIngest } from './src/api/cfb-live';
import type { Env } from './src/types';

export default {
  ...nextWorker,
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const path = new URL(request.url).pathname;
    if (path === '/api/cfb-live' && request.method === 'GET') return handleCfbLive(request, env);
    if (path === '/api/cfb-live/socket' && request.method === 'GET') return handleCfbLiveSocket(request, env);
    if (path === '/api/internal/cfbd/events' && request.method === 'POST') return handleCfbRelayIngest(request, env);
    return nextWorker.fetch(request, env, ctx);
  },
};
